# -*- coding: utf-8 -*-
"""LT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSAKWNCQoQDpPLUFADK7206KzRzlS0C9
"""

ticket_number = {   'Ritika': 1,
                    'Sam': 4, 
                    'John': 5, 
                    'Aadi': 2,
                    'shreya':7
                }
 
for key, value in ticket_number.items():
    print(key, ' : ', value)

  

N=int(input("Enter the max number of participants="))
for i in range(N):

  import random
  
 
test_list = [1, 4, 5, 2, 7]
  
 
print ("participants lottery tickets no are : " + str(test_list))

random_num = random.choice(test_list)
  

print ("the winner is : " + str(random_num))

